### PR TITLE
Revamped Website

### PR DESCRIPTION
**Pull request by adamharrison**
Just made it a static page, with a super-simple generation script; no Jekyll, Node or other frameworks required. Entirely just markdown files, and a single 9-line ruby script.

The only downside is, that as a single page application, it's required to use somewhat esoteric, because GH pages doesn't provide a mechanism for intercepting calls to lower paths.

Either way, please leave a comment about whether you like it, or hate it, and we'll go from there. I've also updated a bunch of the documentation, as well as separated the keymaps (and removed somewhat confusing wording about option being alt sometimes) for greater clairty.

### CODE REVIEW

**Comment by adamharrison** [comment]
I've left `index.html` on the PR for it to be previewed, but when I merge this, I'll remove it.

**Comment by takase1121** [comment]
I'm not a big fan of this. A lot of the changes brings diminishing benefits.

1. Things that could be done easier/semi easier now is done via ruby scripts. I consider that as a downgrade. (keymap)
2. Reference style markdown links are removed. Putting inline links makes everything messy.
3. Templates could be useful, for example the `baseurl` tag would allow the files to link properly. `/hello/world` with github page fork will resolve to `user.github.io/hello/world`, which is _wrong._ This is just one of the cases where it could help.
4. i18n is gone.

**Comment by adamharrison** [comment]
> Things that could be done easier/semi easier now is done via ruby scripts. I consider that as a downgrade. (keymap)

Well, so there's a single instance of a script here. Maybe I'm misunderstanding, but wasn't the keymap previous generated by the scripts/keymap-generator/keymap-generator.lua? Which was a 75-line script, with a 22k supporting library? 

I'd honestly think that's an upgrade; something that was in a different repo, in a different language than the site generator, with a decent-sized suporting library that outputs in json format, that then's interpeted by ruby running markdown, running liquid, to finally spit out a markdown file that's then interpeted to be HTML. That was my understanding of the process, anyway.

With this method, it's a 9 line ruby script generating markdown directly, then being interpreted to HTML. Seems cleaner?

If you mean that originally we were just modifying the .json file directly, then I'm wholeheartedly for that, in the sense that I'd be totally OK with just nixing the script, and maintaining the markdown files manually. Seems even less complicated; I just assumed that we'd want something automatic.

> Reference style markdown links are removed. Putting inline links makes everything messy.

I kept references in where I thought they made sense (i.e. where there's a lot of links in a list); but I recognise that's more a style thing. I find it honestly more readable to simply have the links in-line where they're defined, so you don't have to go scrolling down and hunting for particular numbers outside of where you're actually reading.

But that said; again, I recognize this is a style thing, and am happy to change this back.

> Templates could be useful, for example the baseurl tag would allow the files to link properly. /hello/world with github page fork will resolve to user.github.io/hello/world, which is wrong. This is just one of the cases where it could help.

Well, the router for the entire product is about 5 lines of code, so this could easily be accomodated.

> i18n is gone.

This is a problem, and was an oversight by me. I'd be happy to fix this.

**Comment by adamharrison** [comment]
> i18n is gone.

Also, to be clear; unless I missed something, currently english was the only extant locale, right?

**Comment by adamharrison** [comment]
Ok, I've added back in support for internationalisation. In the meantime, I'm going to revert the website back until we have a bit more consensus here. I am still happy to scrap this as a bad idea if people are opposed; but I'm going to continue to work on getting things a bit cleaner/nicer/better.

**Comment by takase1121** [comment]
> Well, so there's a single instance of a script here. Maybe I'm misunderstanding, but wasn't the keymap previous generated by the scripts/keymap-generator/keymap-generator.lua? Which was a 75-line script, with a 22k supporting library?

keymap-generator.lua AFAIK emulates lite-xl to a degree where it can directly run the keymap and get the keycombos. It's not related to how keymap is "inserted" into html.

**Comment by adamharrison** [comment]
> keymap-generator.lua AFAIK emulates lite-xl to a degree where it can directly run the keymap and get the keycombos. It's not related to how keymap is "inserted" into html.

No I know, I'm aware it's rendered with liquid. I'm basically saying that this script not only replaces the liquid parser/render step of the thing, but also the lua stuff. Quite frankly, it's mainly the lua stuff.

I guess, my point is, is that if the keymap scrape is run on the regular, then we should probably keep a script around for it. If it's run once (as it seems to be; like the master branch here has notes which aren't accounted for in the original export script, so those were likely manually managed); then we should probably just eliminate the script entirely and maintain it in markdown. 

My point is that there's no real reason to have this in JSON, if it's manually maintained. It's also breaking i18n as it is. Just putting in a markdown file directly fixes all those problems.

**Comment by takase1121** [comment]
> I guess, my point is, is that if the keymap scrape is run on the regular, then we should probably keep a script around for it. If it's run once (as it seems to be; like the master branch here has notes which aren't accounted for in the original export script, so those were likely manually managed); then we should probably just eliminate the script entirely and maintain it in markdown.

Sure. That makes more sense since lite-xl own keymap rarely changes.

Perhaps it might be useful to snoop plugin's keymap, but as it stands my script still can't do that. 

Then this should be fine.

**Comment by adamharrison** [comment]
OK, I've reverted all the footnote-style links back to footnote-style links. I've removed the keymap script entirely, as we can just maintain the keymap in markdown, and I've also actually reverted the baseurl stuff, too, and just used relative paths; because we're actually always at the root on a single-page app, so that's a standard way of just sidestepping the whole issue without actually writing any code, that doesn't seem to have any downsides as far as I can see.

**Comment by adamharrison** [comment]
OK, this is ready to go. I'll leave it up for another few days, but if there are no further objections to it, (I think I've addressed all of Takase's and made the requested changes; takase, please correct me if I'm wrong), I'll merge it in.

**Comment by takase1121** [comment]
> OK, this is ready to go. I'll leave it up for another few days, but if there are no further objections to it, (I think I've addressed all of Takase's and made the requested changes; takase, please correct me if I'm wrong), I'll merge it in.

I'm good.

**Pull request merged**
