### PR TITLE
Better keys

### PR DESCRIPTION
**Pull request by takase1121**
This makes the keymap better.

image

If you hover over the keys, the tooltip will be displayed.

### CODE REVIEW

**Comment by franko** [comment]
Hello,

I can see the notifications for the website modifications now, before I was unaware of what was going on.

Otherwise you don't need my validation for your work so you can proceed as you was doing before, I just wanted the notifications.

For this specific PR I like the result but I cannot judge for the code, I guess it is fine.

**Comment by redtide** [comment]
So why delegate to other contributors and then tell that anyone can go ahead without discussing with others?

**Comment by franko** [comment]
> So why delegate to other contributors and then tell that anyone can go ahead without discussing with others?

I apologize but I really don't understand you question. I told to anyone to go ahead without discussing ?

**Comment by redtide** [comment]
From how I parse what you said was a "I can read what you guys do here, so you can commit right away without PR for my approval", when it's not just Takase nor me here working on changes

**Comment by franko** [comment]
> From how I parse what you said was a "I can read what you guys do here, so you can commit right away without PR for my approval", when it's not just Takase nor me here working on changes

My message was for you @redtide and @takase1121 even if I was not explicit. From what I have seen the work on this repository was all made by you two with very specific PR from a few external people.

In reality I expect that if other contributors except you and @takase1121 want to make modifications they go through a PR for a review. On the other side I didn't see any sign that we needed to enforce this.

I meant also that, if I put myself in the repository it is not to check your work but just to be informed of the changes you make. In the past I was not aware of the work you have been doing on the documentation and website in general. And yes, I was complaining about the landing page, my bad! :-)

Otherwise I see that I am pretty bad with communication in general! I will try to improve or maybe be I will just avoid communicating except when strictly required.

I am also thinking about giving the maintainer role for the Lite XL organization and the application's repository to someone else. May be after we release 2.0.2. I will open a discussion about that.

**Comment by redtide** [comment]
Yes, external contributors use PR because they don't have direct data access but PR are also useful to discuss major changes with others, otherwise push right away the simple changes/fixes, I thought also on the lite xl repo works like this.

It's perfectly fine that you can "spy" here, it's your project so your feedback is important, it's not great that other people manage something you started without knowing what's going on and express your preferences.

Was not the complain that hit me, but your sarcasm over a work that took me some days to promote a project that is not mine and I'm not even using yet. So think 2 or more times before tell me how to speak with others in public instead talk privately or point out on defects instead replying on help requests.

About maintenance delegation, if I can put my cent, I was suggesting for Adam.

**Comment by takase1121** [comment]
I'm merging this commit.

**Pull request merged**
